# Use this in your UnturnedImages/config.yaml file
- Id: "56200-56253;56255-56265" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2303050115/items/{ItemId}.png" # The repository of the override.