# Use this in your UnturnedImages/config.yaml file
- Id: "32020" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2171740041/items/{ItemId}.png" # The repository of the override.