# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "1668097797" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/F-Plugins/UnturnedImages@images/modded/1668097797/vehicles/{VehicleId}.png" # The repository of the override.