# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "2978896212" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/F-Plugins/UnturnedImages@images/modded/2978896212/vehicles/{VehicleId}.png" # The repository of the override.